apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-demo
  namespace: edu-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-demo
  template:
    metadata:
      labels:
        app: simple-demo
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-demo
  namespace: edu-platform
spec:
  selector:
    app: simple-demo
  ports:
  - port: 80
    targetPort: 80
